site_name: The Cleaner
site_url: https://cleaner.leodev.xyz/docs/
nav:
    - Rules: rules.md
    - Mitigation Strategies: mitigation.md
    - CAPTCHAs: captchas.md
    - About: about.md
theme: readthedocs